CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL CHECK (role IN ('ADMIN', 'DEALER')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auctions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  item_name VARCHAR(255) NOT NULL,
  start_price DECIMAL(12, 2) NOT NULL,
  current_price DECIMAL(12, 2) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'INACTIVE' CHECK (status IN ('INACTIVE', 'ACTIVE', 'CLOSED')),
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bids (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  auction_id UUID REFERENCES auctions(id) ON DELETE CASCADE,
  dealer_id UUID REFERENCES users(id),
  amount DECIMAL(12, 2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for fast lookup
CREATE INDEX idx_auctions_status ON auctions(status);
CREATE INDEX idx_bids_auction_id ON bids(auction_id);
CREATE INDEX idx_bids_dealer_id ON bids(dealer_id);

-- Wait for Bcrypt hashed passwords to be generated by backend seed script, but we can seed here if we know the hash.
-- Using simple hashing for seeds (password: 'password'):
-- password = $2b$10$EP7XzPIMnJ0I1C9/m8K.oOTmC.w7k/5WpB2.Q90C5O1D2j2.63eBq
INSERT INTO users (id, name, email, password_hash, role) VALUES 
('11111111-1111-1111-1111-111111111111', 'Admin User', 'admin@example.com', '$2b$10$EP7XzPIMnJ0I1C9/m8K.oOTmC.w7k/5WpB2.Q90C5O1D2j2.63eBq', 'ADMIN'),
('22222222-2222-2222-2222-222222222222', 'Dealer One', 'dealer@example.com', '$2b$10$EP7XzPIMnJ0I1C9/m8K.oOTmC.w7k/5WpB2.Q90C5O1D2j2.63eBq', 'DEALER')
ON CONFLICT (email) DO NOTHING;
